### ISSUE TITLE
Markbot infinite screenshot checking

### ISSUE THREAD

**Issue by prim0062** [prim0062/kraken-good-accessibility#1]
When placing the project in Markbot, everything checks and passes successfully, except one screenshot. It never completes the check and just hangs, infinitely checking and preventing me from submitting the exercise.
[Video](https://streamable.com/fjk9n)
@charlie-quinn

**Comment by charlie-quinn** [comment]
This grade has been added manually. 🤖✅

**Comment by charlie-quinn** [comment]
⚠️`Reminder: please close this issue once it has been resolved.`
